# Generated by Django 5.0.3 on 2024-04-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Vegetable',
        ),
    ]
