# Generated by Django 5.0.3 on 2024-04-02 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculate', '0002_delete_fruit_delete_vegetable'),
        ('task_manager', '0005_auto_20240216_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramatur_kertas', models.CharField(max_length=50)),
                ('ukuran_kertas', models.CharField(max_length=50)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipe_kertas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harga', to='task_manager.kalkulatorcetak')),
            ],
        ),
    ]
