# Generated by Django 5.0.3 on 2024-04-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='tipe_kertas',
            field=models.CharField(max_length=50),
        ),
    ]
