# Generated by Django 5.0.3 on 2024-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0004_alter_pricedata_tipe_kertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_cost', models.CharField(max_length=50)),
            ],
        ),
    ]
