# Generated by Django 5.0.3 on 2024-04-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0005_productionprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionprice',
            name='harga_produksi',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
