# Generated by Django 5.0.3 on 2024-04-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0007_laminatecost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishingCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_finishing', models.CharField(max_length=50)),
                ('harga_finishing', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
