# Generated by Django 5.0.3 on 2024-04-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0008_finishingcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laminatecost',
            name='tipe_laminasi',
        ),
        migrations.AddField(
            model_name='laminatecost',
            name='laminate_type',
            field=models.DecimalField(choices=[(0, 'No Laminate'), (0.15, '0.15'), (0.2, '0.2')], decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laminatecost',
            name='length',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laminatecost',
            name='width',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
