# Generated by Django 5.0.3 on 2024-04-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0009_remove_laminatecost_tipe_laminasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionprice',
            name='set_warna',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
