# Generated by Django 5.0.3 on 2024-04-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0010_productionprice_set_warna'),
    ]

    operations = [
        migrations.CreateModel(
            name='DregCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_dreg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ukuran_dreg', models.DecimalField(choices=[(0, 'Tanpa Dreg'), (110, '110'), (120, '120')], decimal_places=2, max_digits=10)),
                ('harga_dreg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
