# Generated by Django 5.0.3 on 2024-04-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0011_dregcost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricedata',
            old_name='gramatur_kertas',
            new_name='plano_besar',
        ),
        migrations.AddField(
            model_name='pricedata',
            name='plano_kecil',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
