# Generated by Django 3.2.25 on 2024-05-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0014_alter_pricedata_ukuran_kertas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='ukuran_kertas',
            field=models.CharField(max_length=50),
        ),
    ]
