# Generated by Django 3.2.25 on 2024-05-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0015_alter_pricedata_ukuran_kertas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricedata',
            name='ukuran_kertas',
        ),
        migrations.AddField(
            model_name='pricedata',
            name='lebar',
            field=models.PositiveIntegerField(default=1, verbose_name='Width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricedata',
            name='panjang',
            field=models.PositiveIntegerField(default=10, verbose_name='Length'),
            preserve_default=False,
        ),
    ]
