# Generated by Django 3.2.25 on 2024-05-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0016_auto_20240506_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricedata',
            name='lebar',
        ),
        migrations.RemoveField(
            model_name='pricedata',
            name='panjang',
        ),
        migrations.AddField(
            model_name='pricedata',
            name='ukuran_kertas',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
