# Generated by Django 3.2.25 on 2024-05-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0018_alter_pricedata_ukuran_kertas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laminatecost',
            name='length',
        ),
        migrations.RemoveField(
            model_name='laminatecost',
            name='width',
        ),
    ]
