# Generated by Django 3.2.25 on 2024-05-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0019_auto_20240506_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='ukuran_kertas',
            field=models.CharField(choices=[('1617', '31 x 49'), ('2144', '31.5 x 64'), ('3072', '48 x 64'), ('6500', '65 x 100'), ('1782', '33 x 54'), ('3519', '51 x 69'), ('1254', '33 x 38'), ('1419', '33 x 43'), ('2014', '38 x 53'), ('2518.5', '34.5 x 73'), ('2584', '38 x 68'), ('3723', '51 x 73'), ('4134', '53 x 78'), ('8611', '79 x 109')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productionprice',
            name='production_cost',
            field=models.CharField(choices=[('300000', '0V 52'), ('350000', '0V 58'), ('450000', '0V 66'), ('500000', '0V 72')], max_length=50),
        ),
    ]
