# Generated by Django 3.1.6 on 2021-02-13 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                ('kode', models.CharField(max_length=200)),
                ('date_spk', models.DateField()),
                ('date_deadline', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('paper', models.CharField(choices=[('AP', 'Art Paper'), ('DUPLEK', 'Duplek'), ('IVORY', 'Ivory'), ('HVS', 'HVS'), ('BONTAC', 'Bontac'), ('BC', 'BC TIK')], max_length=20)),
                ('gramatur', models.CharField(choices=[('80', '80 gsm'), ('100', '100 gsm'), ('120', '120 gsm'), ('150', '150 gsm'), ('190', '190 gsm'), ('210', '210 gsm'), ('230', '230 gsm'), ('250', '250 gsm'), ('260', '260 gsm'), ('300', '300 gsm'), ('310', '310 gsm'), ('350', '350 gsm'), ('400', '400 gsm')], max_length=20)),
                ('sisi', models.CharField(choices=[('1side', '1 Sisi'), ('2side1plate', '2 sisi Balik Plat'), ('2side2plate', '2 sisi Ganti Plat')], max_length=20)),
                ('jumlah_plat', models.CharField(max_length=20)),
                ('uk_bahan_cetak', models.CharField(max_length=20)),
                ('jumlah_cetak', models.CharField(max_length=20)),
                ('jumlah_waste', models.CharField(max_length=20)),
                ('jumlah_kertas', models.CharField(max_length=20)),
                ('laminasi', models.CharField(choices=[('TANPAL','Tanpa Laminasi'), ('GLOSSY','glossy'), ('DOFF','doff')], max_length=20)),
                ('finishing', models.CharField(choices=[('TANPAF', 'Tanpa Finishing'), ('POTONGJADI', 'Potong Jadi'), ('POND', 'Pond'), ('UV', 'Uv Vernish'), ('HOTPRINT', 'Hot Print'), ('KLEMSENG', 'Klemseng'), ('SPIRAL', 'Spiral'), ('EMBOSH', 'Embosh'), ('KANTONG', 'Kantongan'), ('RIT', 'Rit')], max_length=200)),
                ('ukuran_bahan', models.CharField(choices=[('61x86', '61 x 86'), ('65x90', '65 x 90'), ('65x100', '65 x 100'), ('79x109', '79 x 109'), ('70x108', '70 x 108'), ('64x96', '64 x 96'), ('85x120', '85 x 120'), ('65x48', '65 x 48')], max_length=20)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.board')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('name', models.CharField(max_length=50)),                
                # ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('T', 'To Do'), ('D', 'Doing'), ('I', 'In Test'), ('O', 'Done'), ('B', 'Blocked'), ('L', 'Deleted')], max_length=1)),
                ('start_time', models.DateField(null=True)),
                ('end_time', models.DateField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.project')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(through='task_manager.Project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KalkulatorCetak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_kertas', models.CharField(choices=[('ap', 'Art Paper'), ('duplek', 'Duplek'), ('ivory', 'Ivory'), ('hvs', 'HVS'), ('bontac','Bontac'), ('bctik', 'BC TIK')], max_length=50)),
                ('gramatur_kertas', models.CharField(choices=[('80', '80 gsm'), ('100', '100 gsm'), ('120', '120 gsm'), ('150', '150 gsm'), ('190', '190 gsm'), ('210', '210 gsm'), ('230', '230 gsm'), ('250', '250 gsm'), ('260', '260 gsm'), ('310', '310 gsm'), ('350', '350 gsm'), ('400', '400 gsm')], max_length=50)),
                ('ukuran_kertas', models.CharField(choices=[('a4', 'A4'), ('folio', 'Folio'), ('a3', 'A3'), ('a3plus', '32 x 48 (A3+)')], max_length=50)),
            ],
        )
    ]
